version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: qp-assessment
      POSTGRES_USER: grocery-api
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  express:
    environment:
      POSTGRES_USER: grocery-api
      POSTGRES_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_DB: qp-assessment
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
